# Generated by Django 5.0 on 2025-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('total_programs', models.IntegerField()),
                ('approximate_students', models.IntegerField()),
                ('naac_grade', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('contact_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
