# Generated by Django 3.1.13 on 2025-02-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meduv1', '0002_remove_location_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meduv1.university'),
        ),
    ]
