# Generated by Django 3.1.13 on 2025-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meduv1', '0003_location_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='foreign_affiliations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
